### ISSUE TITLE
build query from json

### ISSUE THREAD

**Issue by bsr203** [favclip/smg#9]
Hello,
Thank you for this package. The query builder is good to construct it at the server, but it would be great to have a way to build query from a specification, like json object. say, we have a query struct

```
type filter struct {
    fieldName string
    op        string
    value     interface{}
}

type Query struct {
    filter []filter
    order  []order

    limit  int
    offset int

    keysOnly bool
}
```

if, there is a way to build a query, from this struct, then we can construct query from a json/client request. Do you think it is viable, and any plan for it. Else, how do you typically handle a query from client?

thanks again,
bsr.

**Comment by vvakame** [comment]
Sorry, it is not planed.
I have a question. What is the client? golang or browser(javascript)?

**Comment by bsr203** [comment]
javascript. I use with a react application, and like to build the query from the json payload. I may do the validation of the payload (like filter fields) at the server. It may be nice to have generated code to map this  to a proper smg search query. 

To be honest, I use your `genbase` package extensively for my own generator and yet to look at `smg` thoroughly. I could think of two way to do this
1. strongly typed: then, we generate code for each search type/struct, and use the builder interface while checking the json payload has some of the filters set or not.
2. generic method to build the search query. This doesn't make use of this package but just build a gae search query directly from the payload.

I may be few weeks away from using gae search and my understanding is limited at this moment. If you have a suggestion, I will look into implementing it.

thanks for the quick response.

**Comment by bsr203** [comment]
Hi. I am closing this as I found a solution outside this package. I use a recursive structure to model the query and accept it as json from client. Them map it to gae query and use it. thanks for providing this package and the examples been quite useful.
